function Hd = NotchFilter(fs, Fnotch, BW)
%NOTCHFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 18-Oct-2019 00:50:30

% IIR Notching filter designed using the IIRNOTCH function.

% All passed frequency values are in Hz.
Apass  = 1;   % Bandwidth Attenuation, in dB

[b, a] = iirnotch(Fnotch/(fs/2), BW/(fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
