function Hd = HighPassFilter(fs, FcutHPF)
%HIGHPASSFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Generated on: 16-Oct-2019 09:34:39

% Chebyshev Type I Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
% Sampling Frequency

Fstop = max([1, FcutHPF-2]);        % Stopband Frequency
Fpass = FcutHPF;       % Passband Frequency
Astop = 80;          % Stopband Attenuation (dB)
Apass = 1;           % Passband Ripple (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, fs);
Hd = design(h, 'cheby1', 'MatchExactly', match);

% [EOF]
